### ISSUE TITLE
Things to be fixed

### ISSUE THREAD

**Issue by ifaresse** [swent-group4/sudden-bump#137]
- [x] Find how to bypass SysCall in End-To-End tests
- [x] Send lastKnownLocation to the firebase
- [x] Block the rotation
- [x] SignIn screen always appears at start
- [x] Ask for permission when accessing local storage for uploading profile picture
- [ ] Error handling with toasts
- [x] Harmonize UI to be only black
- [x] Cannot add friend
- [ ] should be able to only add friend with phone number or email address (not simply searching everyone in the DB)
- [x] cannot accept friend request
- [x] gradle seems to be "partially" ignored by git, because when switching branches, dependencies are missing, yet the dependencies are normally in the build.gradle.kts filed pushed to said branch
- [x] page doesn't change after first login, sometimes you have to restart the app to have it set the current user
- [ ] .attach_pidXXXX files created for some reason
- [x] override the hash in user
- [x] message button in overview doesn't navigate to conversation
- [x] settings screen needs redoing
- [x] add friend search box remove line under
- [x] prevent line breaks in text boxes / search bars
- [x] check if meeting request is automatically deleted when the date is due (and meeting hasn't been accepted)
- [x] add app logo and icon name
- [x] check if currentroute == nextroute shouldn't reload UI
- [x] Fix the lag on the Map screen
- [ ] The name of the friends above the marker get far from the marker sometimes
- [x] no profile picture shown in add friends / recommended friends
- [x] friends disappearing and reappearing randomly (linked to friends in several groups?)
- [x] when adding a recommended friend, it should disappear from the recommended people
- [x] Handle the (0,0) location
- [ ] Remove dummy User
- [ ] colors inconsistent
- [ ] search bar in messages screen doesn't work
- [ ] delete messages doesn't delete them properly
- [ ] apk builder

**Comment by marinovdeyan** [comment]
Once the list is established, we need to divide this issue in issues assigned to individual people.
