### ISSUE TITLE
Log out from the app

### ISSUE THREAD

**Issue by daliaghosn** [swent-group4/sudden-bump#262]

**Comment by marinovdeyan** [comment]
While doing this issue, I realized that the way we handle the passing of the Application Context around the different classes was completely wrong. For this reason, the log out kept crashing when clicking the button. We were using getApplicationContext() which is a test-only function and should never be used in the app. I have used the opportunity to refactor a huge bunch of the code for the SharedPreferences and the LocationWorker.
